

services:
  - type: web
    name: g2bulk-aiogram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: G2BULK_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
        


